### ISSUE TITLE
how to pack project to a app？

### ISSUE THREAD

**Issue by zzhgithub** [naviapps/nw-react-boilerplate#1]
sorry I live in china .there is a wall on the Internet .so well i npm install nw.js just can not install success. lol.
and chould you tell how to make it to a Mac dmg?thx.

**Comment by naviapis** [comment]
yet...
I will implement it in the near future.
e.g. `npm run build`

**Comment by naviapis** [comment]
implemented `npm run build`
see `README.md` and `package.json`

**Comment by zzhgithub** [comment]
thx
