### ISSUE TITLE
Import native node modules

### ISSUE THREAD

**Issue by gius80** [naviapps/nw-react-boilerplate#2]
Hi!
I'm trying to figure out how to use native node modules using es6 syntax, but I'm having some issues.

I use this syntax:

import fs from "fs" 

but I get a module not found error ("Module not found: Error: Can't resolve 'fs' in ...)

Any ideas?

Thanks!

**Comment by naviapis** [comment]
fixed it.
insert `target: 'node-webkit'` in `webpack.dev.js` and `webpack.prod.js`.
see https://github.com/naviapps/nw-react-boilerplate/commit/69032f31c4124c8a1a86d7d571d1a61d9c95a60f or master

thanks.
