### ISSUE TITLE
How to use node-usb or other hardware

### ISSUE THREAD

**Issue by ikresoft** [naviapps/nw-react-boilerplate#7]
I am building app which is using node-usb, how can I properly set in webpack not to include this module but nwjs can load it in build or runtime. What I succeed till now is this:
      {
        test: /usb/,
        use: 'null-loader',
      },
but when I make call
import usb from 'usb'
const devices = usb.getDeviceList()

errors are:
Uncaught TypeError: Cannot read property 'devices' of undefined

**Comment by naviapis** [comment]
NW.js supports Chrome Extension API. please use it.
http://docs.nwjs.io/en/latest/References/Chrome%20Extension%20APIs/

```js
// https://developer.chrome.com/apps/hid
chrome.hid.getDevices({}, devices => {
  console.log(devices);
});
```

**Comment by ikresoft** [comment]
Chrome App is good and I am using it in another project, but I would like to use nodejs modules, not to depend on Chrome Ext API, so I make my own gulp script to just transpile js files and its working, only problem I have is manipulating css files from js import clause. Then I found this repository to test and found this problem with native modules
